# Generated by Django 3.2.7 on 2021-12-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_management', '0002_coursepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='country',
            field=models.CharField(default='Poland', max_length=20),
        ),
    ]
