# Generated by Django 3.2.7 on 2021-10-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Files_organizer', '0003_auto_20211009_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programmingpath',
            old_name='image',
            new_name='logo_image',
        ),
        migrations.AddField(
            model_name='programmingpath',
            name='path_image',
            field=models.ImageField(default=1, upload_to='path_images'),
            preserve_default=False,
        ),
    ]
