# Generated by Django 3.2.7 on 2021-10-09 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Files_organizer', '0005_programmingpath_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('programming_path', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Files_organizer.programmingpath')),
            ],
        ),
    ]
