# Generated by Django 3.2.7 on 2021-10-11 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Files_organizer', '0006_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Files_organizer.subject')),
            ],
        ),
    ]
