# Generated by Django 3.2.7 on 2021-10-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Files_organizer', '0007_subtopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
