# Generated by Django 3.2.7 on 2021-10-12 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Files_organizer', '0009_document_studentmaterial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmaterial',
            name='subtopic',
        ),
        migrations.AddField(
            model_name='document',
            name='subtopic',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='Files_organizer.subtopic'),
            preserve_default=False,
        ),
    ]
