# Generated by Django 3.2.7 on 2021-10-12 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Files_organizer', '0010_auto_20211012_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Files_organizer.subject'),
        ),
    ]
