# Generated by Django 3.2.7 on 2021-10-12 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Files_organizer', '0011_alter_subtopic_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmaterial',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
