# Generated by Django 3.2.7 on 2021-10-12 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Files_organizer', '0012_alter_studentmaterial_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmaterial',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Files_organizer.document'),
        ),
    ]
