# Generated by Django 3.2.7 on 2021-10-13 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Files_organizer', '0013_alter_studentmaterial_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmaterial',
            name='subtopic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Files_organizer.subtopic'),
            preserve_default=False,
        ),
    ]
