# Generated by Django 3.2.7 on 2021-10-17 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Files_organizer', '0014_studentmaterial_subtopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='subtopic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Files_organizer.subtopic'),
        ),
        migrations.DeleteModel(
            name='StudentMaterial',
        ),
    ]
