# Generated by Django 3.2.7 on 2021-10-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Files_organizer', '0015_auto_20211017_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('THEORY', 'Theory'), ('EXERCISE', 'Exercise'), ('EXTRA', 'Extra')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
